[package]
name = "drone"
version = "0.1.0"
authors = ["Thomas Deegan <tadeegan@gmail.com>", "Martin Deegan <mddeegan@gmail.com>"]

[dependencies]
rust-pigpio = "0.2.0"
time = "0.1"
sensors = {path = "./sensors", version = "0.1.0"}
debug_server = {path = "./debug", version = "0.1.0"}
protos = {path = "./protos"}
config = {path = "./config"}
protobuf = "1.2.2"
ansi_term = "0.9.0"
i2csensors = {path = "../i2cdev-sensors/i2csensors"} #"0.1.1"
#i2cdev-bmp180 = "0.1.*"
i2cdev-bmp280 = {path = "../i2cdev-sensors/i2cdev-bmp280"}#"0.1.*"#
#i2cdev-l3gd20 = "0.1.*"
#i2cdev-lsm303d = "0.1.*"
i2cdev-lsm9ds0 = {path = "../i2cdev-sensors/i2cdev-lsm9ds0"}#"0.1.*"#
i2cdev = "0.3.1"
unbounded-gpsd = "0.4.1"

[[bin]]
name = "drone"
path = "src/main.rs"

[features]
rpi = []

[profile.dev]
opt-level = 0
debug = true
