[package]
name = "drone"
version = "0.1.0"
authors = ["Thomas Deegan <tadeegan@gmail.com>", "Martin Deegan <mddeegan@gmail.com>"]
build = "build.rs"

[dependencies]
rust-pigpio = "0.1.3"
capnpc = "0.8"
capnp = "0.8"

[[bin]]
name = "drone"
path = "src/main.rs"

