[package]
name = "l3g_gyro"
version = "0.1.0"
authors = ["Thomas Deegan <tadeegan@gmail.com>"]

[dependencies]
time = "0.1"
i2cdev = {path = "../rust-i2cdev"}

[[bin]]
name = "sample"
path = "src/main.rs"

