
# Default configuration file for SafeFlight
# ===== FLIGHT ===== #

[flight.roll]
p = 0.0
i = 0.0
d = 0.0

[flight.pitch]
p = 0.0
i = 0.0
d = 0.0

[flight.yaw]
p = 0.0
d = 0.0

# ===== HARDWARE ===== #

[hardware]
gps = false
wifi_gps = false

# Update rate in Hz - Recommended 100Hz.
# Control Loop can run at a maximum of about 150Hz
# serial = "UART, I2C, SPI"

# Optional Sensor
# [hardware.barometer]
# Available: BMP180, BMP280
# name = "Barometer Model"
# update_rate = 100
# serial = "I2C"

[hardware.gyroscope]
# Available: LSM9DS0, L3GD20
name = "Gyroscope Model"
update_rate = 100
serial = "I2C"

[hardware.accelerometer]
# Available: LSM9DS0, LSM303D, LSM303DLHC
name = "Accelerometer Model"
update_rate = 100
serial = "I2C"

# Optional Sensor
# [hardware.magnetometer]
# Available: LSM9DS0, LSM303D, LSM303DLHC
# name = "Magnetometer Model"
# update_rate = 100
# serial = "I2C"

# Optional Sensor
# [hardware.analog_converter]
# Available: ADS1115
# name = "Analog to Digital Converter"
# update_rate = 100
# serial = "I2C"

[hardware.motors]
pins = [1, 2, 3, 4]
serial_pwm = true
serial = "I2C"

# ===== NETWORKING ===== #

[networking]
server_ip = "0.0.0.0"
server_port = 0

# ===== DEBUG ===== #

[debug]
live_debugging = false
debug_websocket_port = 0
logging = true
motors_off = false
