[package]
name = "configurations"
version = "0.1.0"
authors = ["martindeegan"]

[lib]
name = "configurations"
path =  "src/lib.rs"

[[bin]]
name = "default_generator"
path = "src/main.rs"

[dependencies]
toml = "0.4"
serde = "1.0.8"
serde_derive = "1.0.8"
nalgebra = "0.13.1"
